image: gradle:8-jdk17

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "gradle"
  paths:
    - .gradle/
    - build/

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew build --no-daemon
  artifacts:
    paths:
      - build/libs/*.jar
