image: openjdk:17

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "gradle"
  paths:
    - .gradle/
    - build/
    - ~/.gradle/wrapper/
    - ~/.gradle/caches/

stages:
  - build

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew build --no-daemon
  artifacts:
    paths:
      - build/libs/*.jar
